#!/usr/bin/env python3

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

# This step will configure official Nextcloud image: https://github.com/docker-library/docs/blob/master/nextcloud/README.md

import json
import sys
import socket
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

# Setup default values
host = data.get("host", '')

# Setup environment for nextcloud app, Redis and PHP
config = {
   "PHP_ENABLE_OPCACHE": "1",
   "PHP_MEMORY_LIMIT": "1024M",
   "MYSQL_DATABASE": "nextcloud",
   "MYSQL_HOST": "127.0.0.1",
   "MYSQL_USER": "nextcloud",
   "MYSQL_PASSWORD": "nextcloud",
   "REDIS_HOST": "127.0.0.1",
   "REDIS_HOST_PORT": "6379",
   "OVERWRITEPROTOCOL": "https",
   "NEXTCLOUD_TRUSTED_DOMAINS": host,
   "NEXTCLOUD_DOMAIN": data.get('domain', ''),
   "OVERWRITEHOST": host,
   "COLLABORA_HOST": data.get('collabora_host', ''),
   "NEXTCLOUD_ADMIN_USER": "admin",
   "NEXTCLOUD_ADMIN_PASSWORD": data.get('password', 'Nethesis,1234'),
   "TLS_VERIFY_COLLABORA": f"{data.get('tls_verify_collabora', True)}" # agent.write_envfile does not support boolean
}
agent.write_envfile('config.env', config)

# Setup environment for DB
db_config = {
    "MARIADB_ROOT_PASSWORD": "nextcloud",
    "MARIADB_ROOT_HOST": "localhost",
    "MARIADB_DATABASE": "nextcloud",
    "MARIADB_USER": "nextcloud",
    "MARIADB_PASSWORD": "nextcloud",
    "MARIADB_AUTO_UPGRADE": "true"
}
agent.write_envfile('database.env', db_config)


# For later use and backup
with open('config.json', 'w') as cfp:
    cfp.write(json.dumps(data))
