#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

collabora_host=$(cat config.json | jq -r '.collabora_host // empty')
tls_verify=$(cat config.json | jq -r '.tls_verify_collabora // empty')

if  [[ "$collabora_host" != "" ]]; then
    occ app:install richdocuments
    occ config:app:set richdocuments wopi_url --value=https://$collabora_host
    if [[ "$tls_verify" == 'true' ]]; then
        occ config:app:set richdocuments disable_certificate_verification --value=no
    else
        occ config:app:set richdocuments disable_certificate_verification --value=yes
    fi
    occ app:enable richdocuments
fi
