#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-2.0-only
#

import json
import subprocess
import os
import sys
import agent

counter_script="""
occ user:list -i --output=json <&- | \
    jq -c '[length, map(select(.enabled == true)) | length]'
"""

try:
    with subprocess.Popen(counter_script, stdout=subprocess.PIPE, shell=True, text=True) as fcounter:
        total_users, active_users = json.load(fcounter.stdout)
except Exception as ex:
    print(agent.SD_ERR, ex, file=sys.stderr)
    total_users = 0
    active_users = 0

json.dump({
    "active_users": active_users,
    "total_users": total_users,
}, fp=sys.stdout)
