#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import os
import sys
import json

try:
    with open("config.json") as fcfg:
        user_ldap_domain = json.load(fcfg)["domain"]
except:
    sys.exit(0)

if not user_ldap_domain:
    sys.exit(0)

if not hasattr(agent, 'get_bound_domain_list'):
    sys.exit(0) # core version too old, skip and try on next update

rdb = agent.redis_connect(use_replica=True)
if not agent.get_bound_domain_list(rdb):
    agent.bind_user_domains([user_ldap_domain])
