#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import os
import sys
import json
import agent

config = {}

# Read current configuration from config file
with open('config.json', 'r') as cf:
    config = json.loads(cf.read())

agent.set_env("NEXTCLOUD_TRUSTED_DOMAINS", config["host"])
agent.set_env("NEXTCLOUD_DOMAIN", config.get("domain", ""))

# Setup environment for nextcloud app: DB, Redis and PHP
agent.set_env("PHP_ENABLE_OPCACHE", "1")
agent.set_env("PHP_MEMORY_LIMIT", "1024M")
agent.set_env("MYSQL_DATABASE", "nextcloud")
agent.set_env("MYSQL_HOST", "127.0.0.1")
agent.set_env("MYSQL_USER", "nextcloud")
agent.set_env("MYSQL_PASSWORD", "nextcloud")
agent.set_env("REDIS_HOST", "127.0.0.1")
agent.set_env("REDIS_HOST_PORT", "6379")
agent.set_env("MYSQL_ROOT_PASSWORD", "nextcloud")
agent.set_env("OVERWRITEPROTOCOL", "https")
agent.set_env("OVERWRITEHOST", config.get("domain", ""))
